name: release-please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    uses: Qeteshpony/reusable-workflows/.github/workflows/release-please.yml@main
    with:
      config-file: release.kibot.yml
      board-file: pcb/NTP-Server.kicad_pcb
